frontend:
  replicas: 2
  image:
    repository: ghcr.io/dmitry86/gitops-mini-app-frontend
    tag: "307ce7910c9713a1aaa6f94226cce548a14d31b0"

backend:
  replicas: 1
  image:
    repository: ghcr.io/dmitry86/gitops-mini-app-backend
    tag: "307ce7910c9713a1aaa6f94226cce548a14d31b0"

postgres:
  image: postgres:17-alpine
  database: football
  user: football
  storage: 1Gi
  storageClass: local-path

ingress:
  enabled: true
  className: traefik
